spring:
  profiles:
    active: dev
    
endpoints:
  beans:
    enabled: false
  configprops:
    enabled: false
  docs:
    enabled: false
  dump:
    enabled: false
  env:
    enabled: false
  flyway:
    enabled: false
  health:
    id: health
  info:
    enabled: false
  jmx:
    enabled: false
  jolokia:
    enabled: false
  liquibase:
    enabled: false
  logfile:
    enabled: false
  mappings:
    enabled: false
  metrics:
    enabled: false
  shutdown:
    enabled: false
  trace:
    enabled: false
       
---
spring:
  profiles: dev
 
server:
  port: 12001
 
---
spring:
  profiles: qa
  
server:
  port: 12001
  undertow:
    accesslog:
      dir: /var/log/microservices/providers_mock
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %{i,X-Request-Id} %D'
 